import uiScriptLocale
window = {'name': 'ItemQuestionDialog',
 'style': ('movable', 'float'),
 'x': SCREEN_WIDTH / 2 - 125,
 'y': SCREEN_HEIGHT / 2 - 52,
 'width': 170,
 'height': 105+120,
 'children': ({'name': 'board',
			   'type': 'board',
			   'x': 0,
			   'y': 0,
			   'width': 170,
			   'height': 105+120,
			   'children': ({'name': 'message',
							 'type': 'text',
							 'x': 0,
							 'y': 132,
							 'horizontal_align': 'center',
							 'text': uiScriptLocale.MESSAGE,
							 'text_horizontal_align': 'center',
							 'text_vertical_align': 'center'},
							{'name': 'message2',
							 'type': 'text',
							 'x': 0,
							 'y': 145,
							 'horizontal_align': 'center',
							 'text': uiScriptLocale.MESSAGE,
							 'text_horizontal_align': 'center',
							 'text_vertical_align': 'center'},
							{'name': 'message3',
							 'type': 'text',
							 'x': 0,
							 'y': 158,
							 'horizontal_align': 'center',
							 'text': uiScriptLocale.MESSAGE,
							 'text_horizontal_align': 'center',
							 'text_vertical_align': 'center'},
							{'name': 'deletebutton',
							 'type': 'button',
							 'x': -40,
							 'y': 170,
							 'width': 61,
							 'height': 21,
							 'horizontal_align': 'center',
							 'text': 'Sil',
							 'default_image': 'd:/ymir work/ui/public/middle_button_01.sub',
							 'over_image': 'd:/ymir work/ui/public/middle_button_02.sub',
							 'down_image': 'd:/ymir work/ui/public/middle_button_03.sub'},
							 {
								"name" : "iconslot",
								"type" : "image",

								"x" : 65,
								"y" : 20,

								"image" : "offlineshop/slot/new_base.tga",
								
								"children" :
								(
								
									{
										"name" : "icon",
										"type" : "slot",


										"x" : 4,
										"y" : 4,
										
										"width" : 32,
										"height" : 32,
										
										"slot" : ({"index":0, "x":0, "y":0, "width":32, "height":32,},),
									},					
								),
							},
							{'name': 'sellbutton',
							 'type': 'button',
							 'x': 40,
							 'y': 170,
							 'width': 61,
							 'height': 21,
							 'horizontal_align': 'center',
							 'text': 'Sat',
							 'default_image': 'd:/ymir work/ui/public/middle_button_01.sub',
							 'over_image': 'd:/ymir work/ui/public/middle_button_02.sub',
							 'down_image': 'd:/ymir work/ui/public/middle_button_03.sub'},
							{'name': 'cancelbutton',
							 'type': 'button',
							 'x': 0,
							 'y': 195,
							 'width': 61,
							 'height': 21,
							 'horizontal_align': 'center',
							 'text': '\xddptal',
							 'default_image': 'd:/ymir work/ui/public/middle_button_01.sub',
							 'over_image': 'd:/ymir work/ui/public/middle_button_02.sub',
							 'down_image': 'd:/ymir work/ui/public/middle_button_03.sub'})},)}